CREATE TABLE IF NOT EXISTS `#__simplerenew_accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `managed` TINYINT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `enabled` TINYINT NOT NULL,
  `created_by` INT NULL,
  `created_on` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_on` DATETIME NULL,
  `locked_by` INT NULL,
  `locked_on` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_code` (`code` ASC),
  UNIQUE INDEX `idx_user` (`user_id` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `#__simplerenew_billing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `created_by` INT NULL,
  `created_on` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_on` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account` (`account_id` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `#__simplerenew_coupons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `percent` TINYINT NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `max_redemption` INT NULL,
  `all_plans` TINYINT NOT NULL,
  `enabled` TINYINT NOT NULL,
  `ordering` INT NULL,
  `created_by` INT NULL,
  `created_on` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_on` DATETIME NULL,
  `locked_by` INT NULL,
  `locked_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `#__simplerenew_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `interval_length` INT NOT NULL,
  `interval_unit` VARCHAR(45) NOT NULL,
  `trial_length` INT NOT NULL,
  `trial_unit` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `setup` DECIMAL(10,2) NOT NULL,
  `enabled` TINYINT NULL,
  `ordering` INT NULL,
  `created_by` INT NULL,
  `created_on` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_on` DATETIME NULL,
  `locked_by` INT NULL,
  `locked_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `#__simplerenew_subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `account_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  `coupon_id` INT NULL,
  `status` VARCHAR(45) NOT NULL,
  `current_start` DATE NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `activated` DATE NOT NULL,
  `canceled` DATE NULL,
  `expires` DATE NULL,
  `trial_start` DATE NULL,
  `trial_end` DATE NULL,
  `pending_plan` INT NULL,
  `created_by` INT NULL,
  `created_on` DATETIME NULL,
  `modified_by` INT NULL,
  `modified_on` DATETIME NULL,
  `locked_by` INT NULL,
  `locked_on` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_idx` (`account_id` ASC),
  INDEX `fk_coupon_idx` (`coupon_id` ASC),
  INDEX `fk_plan_idx` (`plan_id` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `#__simplerenew_coupons_plans` (
  `plan_id` INT NOT NULL,
  `coupon_id` INT NOT NULL,
  INDEX `fk_plan_idx` (`plan_id` ASC),
  PRIMARY KEY (`plan_id`, `coupon_id`))
ENGINE = InnoDB;
